import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";
import { Suspense } from "react";
import ClientProvider from "./client-provider";
import { LanguageProps } from "@/i18n";
import { languages } from "../../i18n/settings";

const font = Roboto({ subsets: ["vietnamese"], weight: ["300", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

interface RootLayoutProps extends LanguageProps {
  children: React.ReactNode;
}

export default function RootLayout({
  params: { lang },
  children,
}: Readonly<RootLayoutProps>) {

	return (
    <html lang={lang} data-theme="dark">
      <body className={font.className}>
        <ClientProvider>
              <Suspense>
                <section className="p-2">{children}</section>
              </Suspense>
        </ClientProvider>
      </body>
    </html>
  );
}
