version: '3'

services:
    rabbitmq:
      image: rabbitmq:3.12.14-management-alpine
      container_name: rabbitmq  
      restart: always
      ports:
        - "5672:5672"
        - "15672:15672"
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:

