version: '3.8'

services:
  kafka1:
    image: tjn/kafka:v1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: "kafka_cluster_1"
    volumes:
      - ./props/server.properties:/opt/kafka/config/kraft/server.properties
      - ./data:/tmp/kafka-logs
