server:
  port: 8080

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080
        client:
          client1:
            registration:
              client-id: "client1"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client_credentials"
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/client1-oidc"
              scopes:
                - "user.read"
                - "user.write"
                - "openid"
              require-authorization-consent: true

logging:
  level:
    org.springframework.security: trace