import type { Metadata } from "next";
import Image from "next/image";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import {
  SideBar,
  SideBarContent,
  SideBarFooter,
  SideBarHeader,
  SideBarMenu,
  SideBarMenuItem,
} from "@/components/sidebar";
import ClientProvider from "./client-provider";
import { FaHome } from "react-icons/fa";
import { Box, Flex } from "@/components/ui/layout";
import Link from "next/link";
import { Input } from "@/components/ui/form";

const font = Roboto({ subsets: ["vietnamese"], weight: ["300", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head></head>
      <body className={font.className}>
        <ClientProvider>
          <Flex>
            <SideBar className="bg-secondary">
              <SideBarHeader>
                <Link href={"/admin/dashboard"} className="inline-block">
                  <Flex direction="row" align="center" gap={"2"}>
                    <Image
                      src="https://cdn.icon-icons.com/icons2/2699/PNG/512/atlassian_jira_logo_icon_170511.png"
                      alt="Logo"
                      width={32}
                      height={32}
                    ></Image>
                    <h1 className="text-[28px] leading-9 font-bold text-heading">
                      Charmpy
                    </h1>
                  </Flex>
                </Link>
              </SideBarHeader>
              <SideBarContent>
                <SideBarMenu>
                  <SideBarMenuItem href="/admin/dashboard">
                    <FaHome />
                    <span>Dashboard</span>
                  </SideBarMenuItem>
                  <SideBarMenuItem href="/admin/customers">
                    <FaHome />
                    <span>Customers</span>
                  </SideBarMenuItem>
                  <SideBarMenuItem href="/admin/products">
                    <FaHome />
                    <span>Product</span>
                  </SideBarMenuItem>
									<SideBarMenuItem href="/admin/orders">
                    <FaHome />
                    <span>Orders</span>
                  </SideBarMenuItem>
                </SideBarMenu>
              </SideBarContent>
              <SideBarFooter>
                <SideBarMenu>
                  <SideBarMenuItem href="/admin/profile">
                    <FaHome />
                    <span>Profile</span>
                  </SideBarMenuItem>
                  <SideBarMenuItem href="/admin/settings">
                    <FaHome />
                    <span>Settings</span>
                  </SideBarMenuItem>
									<div>
										<Input type="text" size="md" required/>
									</div>
                </SideBarMenu>
              </SideBarFooter>
            </SideBar>
            <Box className="flex-grow">
              <Suspense>
                <main className="p-2">{children}</main>
              </Suspense>
            </Box>
          </Flex>
        </ClientProvider>
      </body>
    </html>
  );
}
