import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import {
  SideBar,
  SideBarBottom,
  SideBarMenu,
  SideBarMenuItem,
  SideBarTop,
} from "@/components/sidebar";
import ClientProvider from "./client-provider";
import { FaHome } from "react-icons/fa";
import { Box, Flex } from "@/components/ui/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head></head>
      <body className={inter.className}>
        <ClientProvider>
          <Flex>
            <Box>
              <SideBar>
                <SideBarTop>
                  <SideBarMenu>
										<SideBarMenuItem Icon={FaHome} title="Home" badgeContent="5" />
										<SideBarMenuItem Icon={FaHome} title="Home" />
										<SideBarMenuItem Icon={FaHome} title="Home" />
										<SideBarMenuItem Icon={FaHome} title="Home" />
									</SideBarMenu>
                </SideBarTop>
                <SideBarBottom>
								<SideBarMenu>
									<SideBarMenuItem Icon={FaHome} title="Home" />
                  <SideBarMenuItem Icon={FaHome} title="Home" />
									</SideBarMenu>
								</SideBarBottom>
              </SideBar>
            </Box>
            <Box className="flex-grow">
              <Suspense>
                <main>{children}</main>
              </Suspense>
            </Box>
          </Flex>
        </ClientProvider>
      </body>
    </html>
  );
}
