import "@repo/peonyui/styles/peonyui.css";
import "./globals.css";

import type { Metadata } from "next";
import type {ReactNode} from "react";

import { ClientProvider } from "./client-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
