server:
  port: 8082
spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            issuerUri: http://localhost:8080
        registration:
          client1-oidc:
            provider: spring
            clientName:
            clientId: "client1"
            clientSecret: "{noop}secret"
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: "client_secret_basic"
            redirectUri: http://localhost:8082/login/oauth2/code/{registrationId}
            scope:
              - "user.read"
              - "openid"
          client1-authorization-code:
            provider: spring
            clientId: "client1"
            clientSecret: "{noop}secret"
            authorizationGrantType: authorization_code
            redirectUri: http://127.0.0.1:8082/authorized
            scope:
              - "user.read"
            clientName: client1-authorization-code
