version: "3.8"

services:
  kafka1:
    image: tjn/kafka:v1
    container_name: kafka1
    hostname: kafka1
    ports:
      - "8081:8081"
    environment:
      - "KAFKA_CLUSTER_ID=kafkacluster123"
    volumes:
      -  ./props/s1.properties:/opt/kafka/config/kraft/server.properties
      -  ./data/b1:/tmp/kafka-logs

  kafka2:
    image: tjn/kafka:v1
    container_name: kafka2
    hostname: kafka2
    ports:
      - "8082:8082"
    environment:
      - "KAFKA_CLUSTER_ID=kafkacluster123"
    volumes:
      -  ./props/s2.properties:/opt/kafka/config/kraft/server.properties
      -  ./data/b2:/tmp/kafka-logs

  kafka3:
    image: tjn/kafka:v1
    container_name: kafka3
    hostname: kafka3
    ports:
      - "8083:8083"
    environment:
      - "KAFKA_CLUSTER_ID=kafkacluster123"
    volumes:
      -  ./props/s3.properties:/opt/kafka/config/kraft/server.properties
      -  ./data/b3:/tmp/kafka-logs
