version: "3.8"

services:
  kafka1:
    image: tjn/kafka:v1
    container_name: kafka1
    hostname: kafka1
    ports:
      - "19092:19092"
    environment:
      - "KAFKA_CLUSTER_ID=kafkacluster123"
    volumes:
      -  ./props/s1.properties:/opt/kafka/config/kraft/server.properties
      -  kafka1:/tmp/kafka-logs
    networks:
      - ${GLOBAL_NETWORK:-kafka}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2048M'
        reservations:
          memory: '1024M'

  kafka2:
    image: tjn/kafka:v1
    container_name: kafka2
    hostname: kafka2
    ports:
      - "29092:29092"
    environment:
      - "KAFKA_CLUSTER_ID=kafkacluster123"
    volumes:
      -  ./props/s2.properties:/opt/kafka/config/kraft/server.properties
      -  kafka2:/tmp/kafka-logs
    networks:
      - ${GLOBAL_NETWORK:-kafka}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2048M'
        reservations:
          memory: '1024M'

  kafka3:
    image: tjn/kafka:v1
    container_name: kafka3
    hostname: kafka3
    ports:
      - "39092:39092"
    environment:
      - "KAFKA_CLUSTER_ID=kafkacluster123"
    volumes:
      -  ./props/s3.properties:/opt/kafka/config/kraft/server.properties
      -  kafka3:/tmp/kafka-logs
    networks:
      - ${GLOBAL_NETWORK:-kafka}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2048M'
        reservations:
          memory: '1024M'

volumes:
  kafka1:
  kafka2:
  kafka3: